// Generated by CoffeeScript 1.3.1
(function() {

  _.templateSettings = {
    interpolate: /\{\{(.+?)\}\}/g
  };

  this.MAUT = Backbone.View.extend({
    className: "maut",
    tagName: "table",
    solutions: [],
    issues: [],
    addSolution: function(solution) {
      return this.solutions.push(solution);
    },
    addIssue: function(issue) {
      return this.issues.push(issue);
    },
    initialize: function(obj) {
      if (obj == null) {
        obj = {};
      }
      if (obj.solutions instanceof Array) {
        this.solutions = obj.solutions;
      }
      if (obj.issues instanceof Array) {
        return this.issues = obj.issues;
      }
    },
    render: function() {
      var cell, i, issue, row, solution, tbody, _i, _j, _k, _len, _len1, _ref, _ref1, _ref2;
      tbody = $("<tbody></tbody>");
      this.$el.empty().append(tbody);
      row = $("<tr><td></td></tr>");
      _ref = this.solutions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        solution = _ref[_i];
        row.append("<th>" + solution + "</th>");
      }
      tbody.append(row);
      _ref1 = this.issues;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        issue = _ref1[_j];
        row = $("<tr><th>" + issue + "</th></tr>");
        for (i = _k = 1, _ref2 = this.solutions.length; 1 <= _ref2 ? _k <= _ref2 : _k >= _ref2; i = 1 <= _ref2 ? ++_k : --_k) {
          cell = $("<td><label><input type='checkbox'></label></td>");
          row.append(cell);
        }
        tbody.append(row);
      }
      return this;
    }
  });

}).call(this);
