// Generated by CoffeeScript 1.3.1
(function() {

  _.templateSettings = {
    interpolate: /\{\{(.+?)\}\}/g
  };

  ({
    makeVotingThing: function() {
      return $("<div>\n<button class='down'>-</button>\n<input type='number' step='1' min='1' max='10'>\n<button class='up'>+</button>\n</div>");
    }
  });

  this.MAUT = Backbone.View.extend({
    className: "maut",
    tagName: "table",
    solutions: [],
    issues: [],
    addSolution: function(solution) {
      return this.solutions.push(solution);
    },
    addIssue: function(issue) {
      return this.issues.push(issue);
    },
    initialize: function(obj) {
      if (obj == null) {
        obj = {};
      }
      if (obj.solutions instanceof Array) {
        this.solutions = obj.solutions;
      }
      if (obj.issues instanceof Array) {
        return this.issues = obj.issues;
      }
    },
    render: function() {
      var cell, i, issue, row, solution, tbody, _i, _j, _k, _len, _len1, _ref, _ref1, _ref2;
      tbody = $("<tbody></tbody>");
      this.$el.empty().append(tbody);
      row = $("<tr><td></td></tr>");
      _ref = this.solutions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        solution = _ref[_i];
        row.append("<th>" + solution + "</th>");
      }
      tbody.append(row);
      _ref1 = this.issues;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        issue = _ref1[_j];
        row = $("<tr><th>" + issue + "</th></tr>");
        row.append(makeVotingThing());
        for (i = _k = 1, _ref2 = this.solutions.length; 1 <= _ref2 ? _k <= _ref2 : _k >= _ref2; i = 1 <= _ref2 ? ++_k : --_k) {
          cell = $(document.createElement("td"));
          cell.append(makeVotingThing());
          $(".up", cell).click(function(e) {
            var node;
            try {
              node = $(this).siblings('input')[0];
              if (node.value === "") {
                return node.value = $(node).attr('min');
              } else {
                return node.stepUp();
              }
            } catch (e) {

            }
          });
          $(".down", cell).click(function(e) {
            var node;
            try {
              node = $(this).siblings('input')[0];
              if (node.value === "") {
                return node.value = $(node).attr('max');
              } else {
                return node.stepDown();
              }
            } catch (e) {

            }
          });
          row.append(cell);
        }
        tbody.append(row);
      }
      return this;
    }
  });

}).call(this);
